steps:
  - name: 'node:11.10.0'
    args: ['rm', '-rf', 'node_modules']

  - name: 'node:11.10.0'
    args: ['npm', 'i']

  - name: 'node:11.10.0'
    args: ['npm', 'run', 'staging-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gcp-yuito-sandbox/nodejs-api', '.', '-f', 'infra/staging/Dockerfile']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gcp-yuito-sandbox/nodejs-api']
#images: ['gcr.io/gcp-yuito-sandbox/nodejs-api:$SHORT_SHA']
